apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webapp-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: webapp
  namespaceSelector:
    matchNames:
      - test-application
  endpoints:
    - port: "3000"
      interval: 15s
      path: /metrics
